options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd containers/${_IMAGE}
        docker build -t lanlords/${_IMAGE}:latest .
        docker push lanlords/${_IMAGE}:latest
substitutions:
  _IMAGE: unused