options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - 'cd containers/${_IMAGE}'
      - 'docker login --username $$DOCKER_USERNAME --password $$DOCKER_PASSWORD'
      - 'docker build --tag lanlords/${_IMAGE}:latest .'
      - 'docker push lanlords/${_IMAGE}:latest'
      #- |
      #  cd containers/${_IMAGE}
      #  docker login -u $$DOCKER_USERNAME -p $$DOCKER_PASSWORD
      #  docker build -t lanlords/${_IMAGE}:latest .
      #  docker push lanlords/${_IMAGE}:latest
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
availableSecrets:
  secretManager:
    - versionName: projects/lanlords-cloud/secrets/build-docker-username/versions/latest
      env: 'DOCKER_USERNAME'
    - versionName: projects/lanlords-cloud/secrets/build-docker-password/versions/latest
      env: 'DOCKER_PASSWORD'
substitutions:
  _IMAGE: unused
  DOCKER_USERNAME: unused
  DOCKER_PASSWORD: unused