options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        docker build --file containers/${_IMAGE}/Dockerfile \
        --tag lanlords/${_IMAGE}:latest containers/{_IMAGE}
        docker push lanlords/${_IMAGE}:latest
substitutions:
  _IMAGE: unused