options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd containers/${_IMAGE}
        echo ${SECRET_DOCKER_USERNAME}
    secretEnv:
      - SECRET_DOCKER_USERNAME
      - SECRET_DOCKER_PASSWORD
availableSecrets:
  secretManager:
    - env: SECRET_DOCKER_USERNAME
      versionName: projects/lanlords-cloud/secrets/build-docker-username/versions/latest
    - env: SECRET_DOCKER_PASSWORD
      versionName: projects/lanlords-cloud/secrets/build-docker-password/versions/latest
