options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd containers/${_IMAGE}
        echo ${DOCKER_USERNAME}
    secretEnv:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD

availableSecrets:
  secretManager:
    - env: DOCKER_USERNAME
      versionName: projects/lanlords-cloud/secrets/build-docker-username/versions/latest
    - env: DOCKER_PASSWORD
      versionName: projects/lanlords-cloud/secrets/build-docker-password/versions/latest

substitutions:
  _IMAGE: unused
  _DOCKER_USERNAME: ''
  _DOCKER_PASSWORD: ''