options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - 'cd containers/${_IMAGE}'
      - 'docker login --username ${_DOCKER_USERNAME} --password ${_DOCKER_PASSWORD}'
      - 'docker build --tag lanlords/${_IMAGE}:latest .'
      - 'docker push lanlords/${_IMAGE}:latest'
      #- |
      #  cd containers/${_IMAGE}
      #  docker login -u $$DOCKER_USERNAME -p $$DOCKER_PASSWORD
      #  docker build -t lanlords/${_IMAGE}:latest .
      #  docker push lanlords/${_IMAGE}:latest
    secretEnv:
      - '_DOCKER_USERNAME'
      - '_DOCKER_PASSWORD'
availableSecrets:
  secretManager:
    - env: '_DOCKER_USERNAME'
      versionName: projects/lanlords-cloud/secrets/build-docker-username/versions/latest
    - env: '_DOCKER_PASSWORD'
      versionName: projects/lanlords-cloud/secrets/build-docker-password/versions/latest
substitutions:
  _IMAGE: unused
  _DOCKER_USERNAME: unused
  _DOCKER_PASSWORD: unused