options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        cd containers/${_IMAGE}
        echo ${_MY_DOCKER_USERNAME}
    secretEnv:
      - _MY_DOCKER_USERNAME
      - _MY_DOCKER_PASSWORD

availableSecrets:
  secretManager:
    - env: _MY_DOCKER_USERNAME
      versionName: projects/lanlords-cloud/secrets/build-docker-username/versions/latest
    - env: _MY_DOCKER_PASSWORD
      versionName: projects/lanlords-cloud/secrets/build-docker-password/versions/latest

substitutions:
  _IMAGE: unused
  _MY_DOCKER_USERNAME:
  _MY_DOCKER_PASSWORD:
