name: Build Linux Image Template
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: "Short name of the game."

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Image
        run: docker build -t lanlords/${{ inputs.name }} .
        working-directory: containers/${{ inputs.name }}

      # master
      - name: Push Image
        run: docker push lanlords/${{ inputs.name }}
