name: Test Job Template
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: "Short name of the game."

jobs:
  build:
    runs-on: ubuntu-20.04
    needs: check-requirements
    if: ${{ contains(needs.check-requirements.outputs.changed-files-list, 'cod2') || github.event_name == 'schedule' }}
    steps:
      - uses: actions/checkout@v3
      - name: Test Job
        run: echo "${{ needs.check-requirements.outputs.changed-files-list }}"
